module.exports = {
	darkMode: ['class'],
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	theme: {
		extend: {
			borderRadius: {
				sm: 'var(--radius-sm)',
				md: 'var(--radius-md)',
				lg: 'var(--radius-lg)',
				xl: 'var(--radius-xl)',
			},
			colors: {
				background: 'var(--color-background)',
				foreground: 'var(--color-foreground)',
				card: 'var(--color-card)',
				'card-foreground': 'var(--color-card-foreground)',
				popover: 'var(--color-popover)',
				'popover-foreground': 'var(--color-popover-foreground)',
				primary: 'var(--color-primary)',
				'primary-foreground': 'var(--color-primary-foreground)',
				secondary: 'var(--color-secondary)',
				'secondary-foreground': 'var(--color-secondary-foreground)',
				muted: 'var(--color-muted)',
				'muted-foreground': 'var(--color-muted-foreground)',
				accent: 'var(--color-accent)',
				'accent-foreground': 'var(--color-accent-foreground)',
				destructive: 'var(--color-destructive)',
				border: 'var(--color-border)',
				input: 'var(--color-input)',
				ring: 'var(--color-ring)',
				chart: {
					1: 'var(--color-chart-1)',
					2: 'var(--color-chart-2)',
					3: 'var(--color-chart-3)',
					4: 'var(--color-chart-4)',
					5: 'var(--color-chart-5)',
				},
				sidebar: {
					DEFAULT: 'var(--color-sidebar)',
					foreground: 'var(--color-sidebar-foreground)',
					primary: 'var(--color-sidebar-primary)',
					'primary-foreground': 'var(--color-sidebar-primary-foreground)',
					accent: 'var(--color-sidebar-accent)',
					'accent-foreground': 'var(--color-sidebar-accent-foreground)',
					border: 'var(--color-sidebar-border)',
					ring: 'var(--color-sidebar-ring)',
				},
			},
		},
	},
	plugins: [require('tailwindcss-animate'), require('tw-animate-css')],
}
